# Change these first
owner: cimeyclust # Your GitHub organization or username, where this repository lives
repo: Server-Uptime # The name of this repository

sites:
  - name: Website
    url: https://cimeyclust.com
  - name: Panel
    url: https://pterodactyl.cimeyclust.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.cimeyclust.com
  # baseUrl: /your-repo-name
  logoUrl: https://cimeyclust.com/images/CimeyClust-Icon.png
  name: CimeyClust
  introTitle: "**CimeyClust** Services Uptime charts."
  introMessage: These uptime charts are intended to give customers the ability to check on the status of our services at any time, in order to find any errors on their site or ours more quickly. Thanks to Upptime to offer such a good and free software for displaying these informations.
  navbar:
    - title: Status
      href: /
    - title: CimeyClust
      href: https://cimeyclust.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
